{
  "_args": [
    [
      "tryit@https://registry.npmjs.org/tryit/-/tryit-1.0.2.tgz",
      "C:\\gitRepo\\f8app"
    ]
  ],
  "_from": "tryit@>=1.0.1 <2.0.0",
  "_id": "tryit@1.0.2",
  "_inCache": true,
  "_location": "/tryit",
  "_phantomChildren": {},
  "_requested": {
    "name": "tryit",
    "raw": "tryit@https://registry.npmjs.org/tryit/-/tryit-1.0.2.tgz",
    "rawSpec": "https://registry.npmjs.org/tryit/-/tryit-1.0.2.tgz",
    "scope": null,
    "spec": "https://registry.npmjs.org/tryit/-/tryit-1.0.2.tgz",
    "type": "remote"
  },
  "_requiredBy": [
    "/is-resolvable"
  ],
  "_resolved": "https://registry.npmjs.org/tryit/-/tryit-1.0.2.tgz",
  "_shasum": "c196b0073e6b1c595d93c9c830855b7acc32a453",
  "_shrinkwrap": null,
  "_spec": "tryit@https://registry.npmjs.org/tryit/-/tryit-1.0.2.tgz",
  "_where": "C:\\gitRepo\\f8app",
  "author": {
    "email": "henrik@andyet.net",
    "name": "Henrik Joreteg"
  },
  "bugs": {
    "url": "https://github.com/HenrikJoreteg/tryit/issues"
  },
  "dependencies": {},
  "description": "Module to wrap try-catch for better performance and cleaner API.",
  "devDependencies": {
    "tap-spec": "^2.1.2",
    "tape": "^3.0.3"
  },
  "homepage": "https://github.com/HenrikJoreteg/tryit#readme",
  "keywords": [
    "errors",
    "try",
    "errorhandling"
  ],
  "license": "MIT",
  "main": "tryit.js",
  "name": "tryit",
  "optionalDependencies": {},
  "readme": "# tryit\n\nTiny module wrapping try/catch in JavaScript. \n\nIt's *literally 11 lines of code*, [just read it](tryit.js) that's all the documentation you'll need.\n\n\n## install\n\n```\nnpm install tryit\n```\n\n## usage \n\nWhat you'd normally do:\n```js\ntry {\n    dangerousThing();\n} catch (e) {\n    console.log('something');\n}\n```\n\nWith try-it (all it does is wrap try-catch)\n```js\nvar tryit = require('tryit');\n\ntryit(dangerousThing);\n```\n\nYou can also handle the error by passing a second function\n```js\ntryit(dangerousThing, function (e) {\n    if (e) {\n        console.log('do something');\n    }\n})\n```\n\nThe second function follows error-first pattern common in node. So if you pass a callback it gets called in both cases. But will have an error as the first argument if it fails.\n\n## WHAT? WHY DO THIS!? \n\nPrimary motivation is having a clean way to wrap things that might fail, where I don't care if it fails. I just want to try it. \n\nThis includes stuff like blindly reading/parsing stuff from localStorage in the browser. If it's not there or if parsing it fails, that's fine. But I don't want to leave a bunch of empty `catch (e) {}` blocks in the code.\n\nObviously, this is useful any time you're going to attempt to read some unknown data structure.\n\nIn addition, my understanding is that it's hard for JS engines to optimize code in try blocks. By actually passing the code to be executed into a re-used try block, we can avoid having to have more than a single try block in our app. Again, this is not a primary motivation, just a potential side benefit. \n\n\n## license\n\n[MIT](http://mit.joreteg.com/)\n",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/HenrikJoreteg/tryit.git"
  },
  "scripts": {
    "test": "node test/test.js | tap-spec"
  },
  "version": "1.0.2"
}
